### ISSUE TITLE
[BUG] Black background of navigationBar in iOS 15

### ISSUE THREAD

**Issue by NullIsOne** [chausovSurfStudio/SurfPlaybook#10]
**Describe the bug**
Black background of navigationBar in iOS 15

**To Reproduce**
1. Open PlaybookApp target on device

**Expected behavior**
White  background of navigationBar

**Screenshots**
<img src="https://user-images.githubusercontent.com/28707156/146364362-e309e289-1f11-496c-94f0-d06f2011590a.png" width="200">

https://user-images.githubusercontent.com/28707156/146364494-a927795b-a0ec-4f9e-8347-34bd439cdfb0.mp4

**Library version and device type**
 - iOS version: 15.0
 - device type: all
 - Version 1.2.2

**Additional context**
In iOS 15 we have broken `barTintColor`.  More info in [answer](https://developer.apple.com/forums/thread/682420)
We must configure background using `UINavigationBarAppearance.backgroundColor`.
You could fix it in library, but I have **workaround** using global appearances.

Just add and call next func in `PlaybookBuilder`

```
func configureNavigationBar() {

        let appearance = UINavigationBarAppearance()
        appearance.configureWithOpaqueBackground()
        appearance.backgroundColor = .white

        UINavigationBar.appearance().standardAppearance = appearance
        UINavigationBar.appearance().scrollEdgeAppearance = appearance

    }
```

**Comment by chausovSurfStudio** [comment]
thanks for feedback ❤️ 
released in version [1.3.0](https://github.com/surfstudio/SurfPlaybook/releases/tag/1.3.0)
